---
- name: Converge
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: "Include postgres role"
      ansible.builtin.include_role:
        name: "postgres"
        tasks_from: main.yml
